-- Super admin flag
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_super_admin BOOLEAN DEFAULT FALSE;

-- Timestamps
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE users   ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Plan limits for tenants
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS max_users   INTEGER DEFAULT 10;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255);
